backend:
  name: git-gateway
  branch: master  
  repo: chihiroj/blog

local_backend: true

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "/public/content/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "layout", label: "Layout", widget: "hidden", default: "articles" }
      - { name: "title", label: "Title", widget: "string" }