backend:
  name: git-gateway
  branch: master  
  repo: chihiroj/blog

local_backend: true

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "/public/content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "string" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "category", label: "Category", widget: "string" }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "featured", label: "Featured", widget: "boolean" }
