backend:
  name: git-gateway
  branch: master  
  repo: chihiroj/blog

local_backend: true

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "/public/content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "string" }
      - { name: "author", label: "Author", widget: "relation", collection: "authors", search_fields: ["name"], value_field: "name", display_fields: ["name"] }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "categories", label: "Categories", widget: "relation", collection: "categories", search_fields: ["category"], value_field: "category", display_fields: ["category"], multiple: true }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "featured", label: "Featured", widget: "boolean" }
  - name: "authors"
    label: "Authors"
    folder: "/public/content/authors"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "name", label: "Name", widget: "string" }
  - name: "categories"
    label: "Categories"
    folder: "/public/content/category"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "category", label: "Category", widget: "string" }